x-common-settings:
  chain-settings: &chain-settings
    image: stc-chain
    healthcheck:
      test: ["CMD", "/bin/bash", "/app/check_healthy.sh"]
      interval: 6s
      timeout: 5s
      retries: 10
  
  storage-settings: &storage-settings
    image: stc-storage-node
    depends_on:
      storage-contract-deployer:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD", "/bin/bash", "/app/check_healthy.sh"]
      interval: 6s
      timeout: 5s
      retries: 10


services:
  chain0:
    <<: *chain-settings
    ports:
      - 14000:8545
    command: ./launch_node.sh 0

  chain1:
    <<: *chain-settings
    command: ./launch_node.sh 1

  chain2:
    <<: *chain-settings
    command: ./launch_node.sh 2

  chain3:
    <<: *chain-settings
    command: ./launch_node.sh 3

  storage-contract-deployer:
    image: stc-storage-contracts
    volumes:
      - ./storage-contracts/cache:/root/.cache
    depends_on:
      chain0:
        condition: service_healthy
    command: ./deploy_contracts.sh

  storage0:
    <<: *storage-settings
    ports:
      - 15000:5678
    command: ./launch_node.sh 0

  storage1:
    <<: *storage-settings
    ports:
      - 15001:5678
    command: ./launch_node.sh 1

  storage2:
    <<: *storage-settings
    ports:
      - 15002:5678
    command: ./launch_node.sh 2

  storage3:
    <<: *storage-settings
    ports:
      - 15003:5678
    command: ./launch_node.sh 3

  # indexer:
  #   image: stc-storage-client
  #   depends_on:
  #     storage0:
  #       condition: service_healthy
  #     storage1:
  #       condition: service_healthy
  #     storage2:
  #       condition: service_healthy
  #     storage3:
  #       condition: service_healthy
  #   ports:
  #     - 12345:12345
  #   command: ./0g-storage-client indexer --trusted http://storage0:5678,http://storage1:5678,http://storage2:5678,http://storage3:5678
    
  kv:
    image: stc-storage-kv
    ports:
      - 16000:6789
    depends_on:
      storage0:
        condition: service_healthy
      storage1:
        condition: service_healthy
      storage2:
        condition: service_healthy
      storage3:
        condition: service_healthy
    command: ./zgs_kv --config config.toml

    
